### ISSUE TITLE
 psql `\password` meta-command 

### ISSUE THREAD

**Issue by tsoulabail** [HexaCluster/credcheck#41]
I use the credcheck extension and my plain text password is like 'Unmotdepasse_123'.
I get feedback that seems abnormal (abnormal or not ?) with the psql `\password` meta-command :
`ERROR:  password type is not a plain text`

For the psql `\password` meta command to execute correctly, I pushed `credcheck.encrypted_password_allowed = on`
The documentation does not explain this case.
Thanks for your response

**Comment by tsoulabail** [comment]
The `\password` metacommand of `psql` calls the `PQchangePassword` function, a libpq function.
And `PQchangePassword` in turn calls another function `PQencryptPasswordConn`which encrypts the password before sending it to the server.
So with `\password` the new password is transmitted to the PostgreSQL server in encrypted form.
Sources : 
https://github.com/postgres/postgres/blob/master/src/bin/psql/command.c#L2225
https://github.com/postgres/postgres/blob/master/src/interfaces/libpq/fe-auth.c#L1417 
 
If `credcheck.encrypted_password_allowed = off` i can't use  `\password` metacommand as `ALTER ROLE ... PASSWORD`.
And if `credcheck.encrypted_password_allowed = on` , with an encypt password , credcheck rules for password control can be bypassed.
It's a limitation that you explain in README.md : "This extension only works for the plain text passwords."

Thanks

**Comment by darold** [comment]
Commit 34c1dcf adds a note about the `\password` psql command. Thanks.
