### ISSUE TITLE
Credcheck-credcheck.max_auth_failure

### ISSUE THREAD

**Issue by Kennycwc** [HexaCluster/credcheck#43]
In the use of the Credcheck suite, the parameter "credcheck.max_auth_failure = '3'" is set in the postgresql.conf file to limit users from entering incorrect passwords more than three times, after which their account will be locked. Due to certain requirements, I would like to ask if there is a way or feature to set this parameter differently for a specific user or role, so that it does not apply to them.

I considered using "credcheck.whitelist" to exclude certain accounts, but this would cause all other parameters to apply as well, and the account would still require the other password complexity settings. I only wish to exclude the "credcheck.max_auth_failure" parameter.

Thank you in advance for your response, and I would appreciate any assistance you can provide!

**Comment by darold** [comment]
I have some difficulties to understand the logic to exclude a user for the max authentication failure feature, can you explain the reason of the feature request?

**Comment by Kennycwc** [comment]
We have both regular accounts and system accounts. For regular accounts, we still require password complexity and the lockout functionality after multiple failed login attempts. However, for system accounts, due to information security regulations, password complexity is also required. The issue is that system accounts are used for system integration, and if the account gets locked, it may affect system services, which could lead to problems. To prevent this, we would like to exclude system accounts from being affected by the credcheck.max_auth_failure parameter.

Thanks !

**Comment by Kennycwc** [comment]
We have an idea here and are wondering if it is possible to implement a syntax similar to the one in the image below to set parameters for specific accounts?

**Comment by Kennycwc** [comment]
We have an idea here and are wondering if it is possible to implement a syntax similar to the one below to set parameters for specific accounts?

EX : ALTER ROLE apkenny set credcheck.failed_attempts = -1;

**Comment by darold** [comment]
Commit 1729abf adds this feature.

The ALTER ROLE can not be used because the authentication hook doesn't allow to use a database to look at PG catalog.
Use the following to exclude a list of user from being banned:
```
credcheck.whitelist_auth_failure = 'appuser1,appuser2'
```

**Comment by Kennycwc** [comment]
Thank you very much for your assistance!!
